import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPage from "./header/page";
import LargeEcommerceFooter from "./footer/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "./cartcontext/cartcontextprovider";
import { Component } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
          suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider>

        <HeaderPage />
        {children}
        <LargeEcommerceFooter />
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: '#f9f9f9', 
              color: '#1b1b1b',    
              border: '1px solid #ddd',
            },
          }}
        />
        </CartContextProvider>
      </body>
    </html>
  );
}
